"""Default ECC profile catalog used to bootstrap a user's local profiles."""

DEFAULT_CONFIG = {
    "schema_version": 1,
    "ecc_home": "~/everything-claude-code",
    "profile_home": "~/.ecc-manager/profiles",
    "link_mode": "symlink",
    "overwrite_policy": "skip",
    "generated_claude_file": "CLAUDE.ecc.generated.md",
    "generated_codex_file": "AGENTS.ecc.generated.md",
    "generated_antigravity_file": "ANTIGRAVITY.ecc.generated.md",
    "enable_claude": True,
    "enable_codex": False,
    "enable_antigravity": False,
    "manage_agents_md": True,
    "manage_settings_json": False,
}


PHASES = {
    "ph-init": {
        "schema_version": 1,
        "id": "ph-init",
        "type": "phase",
        "name_zh": "项目初期",
        "description_zh": "适合从 0 到 1 的早期阶段，重点是需求澄清、MVP 范围、技术选型和架构规划。",
        "required": {
            "commands": ["plan.md", "plan-prd.md"],
            "rules": ["common"],
            "skills": ["context-budget", "strategic-compact", "codebase-onboarding", "coding-standards", "api-design"],
            "agents": ["planner.md", "code-architect.md", "code-explorer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "ph-build": {
        "schema_version": 1,
        "id": "ph-build",
        "type": "phase",
        "name_zh": "功能开发中",
        "description_zh": "适合构建 MVP 和核心功能，小步迭代并保持验证闭环。",
        "required": {
            "commands": ["plan.md"],
            "rules": ["common"],
            "skills": ["search-first", "iterative-retrieval", "verification-loop", "tdd-workflow", "coding-standards", "context-budget"],
            "agents": ["planner.md", "code-explorer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "ph-onboard": {
        "schema_version": 1,
        "id": "ph-onboard",
        "type": "phase",
        "name_zh": "接手已有项目",
        "description_zh": "适合先理解已有项目结构、技术栈、关键模块和验证命令。",
        "required": {
            "commands": ["plan.md", "project-init.md"],
            "rules": ["common"],
            "skills": ["codebase-onboarding", "code-tour", "search-first", "iterative-retrieval", "context-budget", "strategic-compact"],
            "agents": ["code-explorer.md", "planner.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "ph-iterate": {
        "schema_version": 1,
        "id": "ph-iterate",
        "type": "phase",
        "name_zh": "已有项目二次开发",
        "description_zh": "适合在理解现有结构后进行功能迭代，强调小步修改和遵守项目原有模式。",
        "required": {
            "commands": ["plan.md"],
            "rules": ["common"],
            "skills": ["search-first", "iterative-retrieval", "verification-loop", "coding-standards", "context-budget"],
            "agents": ["code-explorer.md", "planner.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "ph-qa": {
        "schema_version": 1,
        "id": "ph-qa",
        "type": "phase",
        "name_zh": "后期质量检查",
        "description_zh": "适合功能基本完成后的构建修复、代码审查、测试覆盖和安全问题排查。",
        "required": {
            "commands": ["plan.md", "code-review.md", "build-fix.md", "test-coverage.md"],
            "rules": ["common"],
            "skills": ["verification-loop", "security-review", "error-handling", "tdd-workflow"],
            "agents": ["code-reviewer.md", "build-error-resolver.md", "security-reviewer.md", "silent-failure-hunter.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "ph-launch": {
        "schema_version": 1,
        "id": "ph-launch",
        "type": "phase",
        "name_zh": "上线发布前",
        "description_zh": "适合发布前的安全、部署、性能、成本和质量检查。",
        "required": {
            "commands": ["plan.md", "code-review.md", "security-scan.md", "quality-gate.md"],
            "rules": ["common"],
            "skills": ["production-audit", "deployment-patterns", "security-review", "cost-tracking", "verification-loop"],
            "agents": ["security-reviewer.md", "performance-optimizer.md", "code-reviewer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
}


ARCHITECTURES = {
    "arch-web-saas-next-postgres": {
        "schema_version": 1,
        "id": "arch-web-saas-next-postgres",
        "type": "architecture",
        "preset_kind": "architecture",
        "name_zh": "网站 / SaaS 全栈",
        "description_zh": "完整 Web 应用架构：Next.js 前端、TypeScript、API、Postgres、Prisma、数据库迁移和错误处理。",
        "includes": {"project-types": ["saas-next-fullstack"]},
        "required": {
            "commands": [],
            "rules": [],
            "skills": ["make-interfaces-feel-better", "browser-qa", "e2e-testing"],
            "agents": ["e2e-runner.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "arch-ai-agent-fastapi-web": {
        "schema_version": 1,
        "id": "arch-ai-agent-fastapi-web",
        "type": "architecture",
        "preset_kind": "architecture",
        "name_zh": "AI Agent 应用",
        "description_zh": "完整 AI 应用架构：Python Agent、FastAPI API、Web UI、eval、prompt 优化和成本控制。",
        "includes": {"project-types": ["ai-agent-python", "api-python-fastapi"]},
        "required": {
            "commands": [],
            "rules": ["typescript", "web"],
            "skills": ["frontend-patterns", "frontend-design-direction", "browser-qa"],
            "agents": ["typescript-reviewer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "arch-crawler-data-platform": {
        "schema_version": 1,
        "id": "arch-crawler-data-platform",
        "type": "architecture",
        "preset_kind": "architecture",
        "name_zh": "爬虫与数据平台",
        "description_zh": "完整数据平台架构：Python 采集、数据清洗、Postgres 存储、API 服务和轻量 Web 展示。",
        "includes": {"project-types": ["crawler-python-data", "api-python-fastapi"]},
        "required": {
            "commands": [],
            "rules": ["typescript", "web"],
            "skills": ["frontend-patterns", "browser-qa"],
            "agents": ["typescript-reviewer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "arch-browser-extension-with-api": {
        "schema_version": 1,
        "id": "arch-browser-extension-with-api",
        "type": "architecture",
        "preset_kind": "architecture",
        "name_zh": "浏览器扩展 + API",
        "description_zh": "完整扩展应用架构：Chrome Extension、Web UI、E2E、安全检查和 Node API 后端。",
        "includes": {"project-types": ["browser-extension-chrome", "api-node-backend"]},
        "required": {
            "commands": [],
            "rules": [],
            "skills": ["frontend-design-direction"],
            "agents": [],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "arch-devops-automation-platform": {
        "schema_version": 1,
        "id": "arch-devops-automation-platform",
        "type": "architecture",
        "preset_kind": "architecture",
        "name_zh": "DevOps 自动化平台",
        "description_zh": "完整自动化平台架构：Python 自动化脚本、Docker、部署、安全、成本和网络配置检查。",
        "includes": {"project-types": ["automation-script-python", "infra-docker-devops"]},
        "required": {
            "commands": [],
            "rules": [],
            "skills": [],
            "agents": [],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
}


PROJECT_TYPES = {
    "saas-next-fullstack": {
        "schema_version": 1,
        "id": "saas-next-fullstack",
        "type": "project-type",
        "name_zh": "Next.js SaaS 全栈",
        "description_zh": "适合 Next.js / TypeScript / SaaS 全栈项目。",
        "required": {
            "commands": [],
            "rules": ["typescript", "web"],
            "skills": ["frontend-patterns", "frontend-design-direction", "backend-patterns", "api-design", "database-migrations", "postgres-patterns", "prisma-patterns", "error-handling"],
            "agents": ["typescript-reviewer.md", "database-reviewer.md", "performance-optimizer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "web-react-frontend": {
        "schema_version": 1,
        "id": "web-react-frontend",
        "type": "project-type",
        "name_zh": "React 前端",
        "description_zh": "适合 React / TypeScript / Web UI 项目。",
        "required": {
            "commands": [],
            "rules": ["typescript", "web"],
            "skills": ["frontend-patterns", "frontend-design-direction", "make-interfaces-feel-better", "motion-ui", "accessibility", "browser-qa", "e2e-testing"],
            "agents": ["typescript-reviewer.md", "a11y-architect.md", "e2e-runner.md", "performance-optimizer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "api-node-backend": {
        "schema_version": 1,
        "id": "api-node-backend",
        "type": "project-type",
        "name_zh": "Node API 后端",
        "description_zh": "适合 Node.js / NestJS / TypeScript API 服务。",
        "required": {
            "commands": [],
            "rules": ["typescript"],
            "skills": ["backend-patterns", "nestjs-patterns", "api-design", "database-migrations", "postgres-patterns", "prisma-patterns", "error-handling", "docker-patterns"],
            "agents": ["code-architect.md", "typescript-reviewer.md", "database-reviewer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "api-python-fastapi": {
        "schema_version": 1,
        "id": "api-python-fastapi",
        "type": "project-type",
        "name_zh": "FastAPI 后端",
        "description_zh": "适合 Python / FastAPI API 服务。",
        "required": {
            "commands": [],
            "rules": ["python"],
            "skills": ["python-patterns", "python-testing", "fastapi-patterns", "backend-patterns", "api-design", "database-migrations", "postgres-patterns", "error-handling"],
            "agents": ["python-reviewer.md", "fastapi-reviewer.md", "database-reviewer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "api-python-django": {
        "schema_version": 1,
        "id": "api-python-django",
        "type": "project-type",
        "name_zh": "Django 后端",
        "description_zh": "适合 Python / Django 后端项目。",
        "required": {
            "commands": [],
            "rules": ["python"],
            "skills": ["python-patterns", "python-testing", "django-patterns", "django-security", "django-tdd", "django-verification", "database-migrations", "postgres-patterns"],
            "agents": ["python-reviewer.md", "django-reviewer.md", "database-reviewer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "ai-agent-python": {
        "schema_version": 1,
        "id": "ai-agent-python",
        "type": "project-type",
        "name_zh": "Python AI Agent",
        "description_zh": "适合 Python Agent、LLM workflow、eval 和 agent harness 项目。",
        "required": {
            "commands": [],
            "rules": ["python"],
            "skills": ["agentic-engineering", "agent-harness-construction", "agent-architecture-audit", "ai-regression-testing", "eval-harness", "prompt-optimizer", "cost-aware-llm-pipeline", "python-patterns"],
            "agents": ["code-architect.md", "python-reviewer.md", "security-reviewer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "automation-script-python": {
        "schema_version": 1,
        "id": "automation-script-python",
        "type": "project-type",
        "name_zh": "Python 自动化脚本",
        "description_zh": "适合本地自动化、运维脚本、CLI 小工具。",
        "required": {
            "commands": [],
            "rules": ["python"],
            "skills": ["python-patterns", "python-testing", "terminal-ops", "error-handling", "automation-audit-ops", "coding-standards"],
            "agents": ["python-reviewer.md", "code-explorer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "crawler-python-data": {
        "schema_version": 1,
        "id": "crawler-python-data",
        "type": "project-type",
        "name_zh": "Python 爬虫与数据",
        "description_zh": "适合爬虫、数据采集、清洗和存储项目。",
        "required": {
            "commands": [],
            "rules": ["python"],
            "skills": ["python-patterns", "data-scraper-agent", "terminal-ops", "error-handling", "postgres-patterns", "documentation-lookup"],
            "agents": ["python-reviewer.md", "code-explorer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "browser-extension-chrome": {
        "schema_version": 1,
        "id": "browser-extension-chrome",
        "type": "project-type",
        "name_zh": "Chrome 浏览器扩展",
        "description_zh": "适合 Chrome extension / WebExtension 项目。",
        "required": {
            "commands": [],
            "rules": ["typescript", "web"],
            "skills": ["frontend-patterns", "browser-qa", "e2e-testing", "accessibility", "security-review"],
            "agents": ["typescript-reviewer.md", "e2e-runner.md", "security-reviewer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "ml-python-pipeline": {
        "schema_version": 1,
        "id": "ml-python-pipeline",
        "type": "project-type",
        "name_zh": "Python ML Pipeline",
        "description_zh": "适合机器学习、评测、实验流水线。",
        "required": {
            "commands": [],
            "rules": ["python"],
            "skills": ["python-patterns", "python-testing", "mle-workflow", "ai-regression-testing", "eval-harness", "benchmark", "cost-aware-llm-pipeline"],
            "agents": ["python-reviewer.md", "mle-reviewer.md", "performance-optimizer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "infra-docker-devops": {
        "schema_version": 1,
        "id": "infra-docker-devops",
        "type": "project-type",
        "name_zh": "Docker / DevOps",
        "description_zh": "适合 Docker、部署、基础设施和网络配置检查。",
        "required": {
            "commands": [],
            "rules": ["common"],
            "skills": ["docker-patterns", "deployment-patterns", "production-audit", "security-review", "cost-tracking", "network-config-validation"],
            "agents": ["security-reviewer.md", "performance-optimizer.md", "network-config-reviewer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
}


PACKS = {
    "code-review-pack": {
        "schema_version": 1,
        "id": "code-review-pack",
        "type": "pack",
        "name_zh": "代码审查包",
        "description_zh": "添加本地代码审查所需命令、技能和 agents。",
        "required": {
            "commands": ["code-review.md"],
            "rules": [],
            "skills": ["verification-loop", "security-review"],
            "agents": ["code-reviewer.md", "security-reviewer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "build-fix-pack": {
        "schema_version": 1,
        "id": "build-fix-pack",
        "type": "pack",
        "name_zh": "构建修复包",
        "description_zh": "添加构建失败、类型错误和静默失败定位能力。",
        "required": {
            "commands": ["build-fix.md"],
            "rules": [],
            "skills": ["verification-loop", "error-handling"],
            "agents": ["build-error-resolver.md", "silent-failure-hunter.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "test-coverage-pack": {
        "schema_version": 1,
        "id": "test-coverage-pack",
        "type": "pack",
        "name_zh": "测试覆盖包",
        "description_zh": "添加测试覆盖率分析和补测试能力。",
        "required": {
            "commands": ["test-coverage.md"],
            "rules": [],
            "skills": ["tdd-workflow", "verification-loop", "python-testing", "cpp-testing", "golang-testing", "kotlin-testing"],
            "agents": [],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "security-audit-pack": {
        "schema_version": 1,
        "id": "security-audit-pack",
        "type": "pack",
        "name_zh": "安全审计包",
        "description_zh": "添加安全扫描、生产审计和安全 reviewer。",
        "required": {
            "commands": ["security-scan.md"],
            "rules": [],
            "skills": ["security-review", "security-scan", "production-audit"],
            "agents": ["security-reviewer.md"],
            "runtime": [],
        },
        "optional": {"hooks": ["security hooks"], "mcp": ["security-related MCP"], "external_install": []},
    },
    "content-docs-pack": {
        "schema_version": 1,
        "id": "content-docs-pack",
        "type": "pack",
        "name_zh": "文档更新包",
        "description_zh": "添加 README、帮助文档、产品说明和文档更新能力。",
        "required": {
            "commands": ["update-docs.md"],
            "rules": [],
            "skills": ["documentation-lookup", "article-writing", "content-engine", "brand-voice"],
            "agents": ["docs-lookup.md", "doc-updater.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "research-writing-pack": {
        "schema_version": 1,
        "id": "research-writing-pack",
        "type": "pack",
        "name_zh": "调研写作包",
        "description_zh": "添加深度调研、市场研究和产品能力分析。",
        "required": {
            "commands": [],
            "rules": [],
            "skills": ["deep-research", "research-ops", "market-research", "product-capability"],
            "agents": ["docs-lookup.md", "comment-analyzer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "seo-content-pack": {
        "schema_version": 1,
        "id": "seo-content-pack",
        "type": "pack",
        "name_zh": "SEO 内容包",
        "description_zh": "添加 SEO 内容、品牌语气和内容生产能力。",
        "required": {
            "commands": [],
            "rules": [],
            "skills": ["seo", "brand-voice", "content-engine"],
            "agents": ["seo-specialist.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "multi-model-planning-pack": {
        "schema_version": 1,
        "id": "multi-model-planning-pack",
        "type": "pack",
        "name_zh": "多模型规划包",
        "description_zh": "添加 multi-* 多模型规划命令。外部 ccg-workflow runtime 和 ace-tool MCP 需要单独确认。",
        "required": {
            "commands": ["multi-plan.md", "multi-execute.md", "multi-backend.md", "multi-frontend.md", "multi-workflow.md"],
            "rules": [],
            "skills": [],
            "agents": [],
            "runtime": ["ccg-workflow"],
        },
        "optional": {
            "hooks": [],
            "mcp": ["ace-tool"],
            "external_install": ["npx ccg-workflow"],
        },
    },
    "prp-workflow-pack": {
        "schema_version": 1,
        "id": "prp-workflow-pack",
        "type": "pack",
        "name_zh": "PRP 需求到交付包",
        "description_zh": "添加 PRP 规划、需求、实现、提交和 PR 工作流命令。",
        "required": {
            "commands": ["prp-plan.md", "prp-prd.md", "prp-implement.md", "prp-commit.md", "prp-pr.md"],
            "rules": ["common"],
            "skills": ["blueprint", "architecture-decision-records", "context-budget", "strategic-compact", "verification-loop"],
            "agents": ["planner.md", "code-architect.md", "code-reviewer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "github-pr-pack": {
        "schema_version": 1,
        "id": "github-pr-pack",
        "type": "pack",
        "name_zh": "GitHub / PR 协作包",
        "description_zh": "添加 PR 创建、PR 审查、GitHub 协作和多 reviewer 分析能力。",
        "required": {
            "commands": ["pr.md", "review-pr.md"],
            "rules": ["common"],
            "skills": ["github-ops", "git-workflow", "verification-loop", "tdd-workflow"],
            "agents": ["code-reviewer.md", "comment-analyzer.md", "pr-test-analyzer.md", "silent-failure-hunter.md", "type-design-analyzer.md", "code-simplifier.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "session-memory-pack": {
        "schema_version": 1,
        "id": "session-memory-pack",
        "type": "pack",
        "name_zh": "会话 / 记忆管理包",
        "description_zh": "添加会话保存恢复、项目列表、checkpoint 和旁路提问能力。",
        "required": {
            "commands": ["save-session.md", "resume-session.md", "sessions.md", "projects.md", "checkpoint.md", "aside.md"],
            "rules": ["common"],
            "skills": ["continuous-learning-v2", "context-budget", "strategic-compact", "knowledge-ops"],
            "agents": ["conversation-analyzer.md", "code-explorer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "continuous-learning-pack": {
        "schema_version": 1,
        "id": "continuous-learning-pack",
        "type": "pack",
        "name_zh": "连续学习包",
        "description_zh": "添加 learn、instinct、evolve、promote、prune 等长期学习和能力沉淀命令。",
        "required": {
            "commands": ["learn.md", "learn-eval.md", "evolve.md", "instinct-status.md", "instinct-import.md", "instinct-export.md", "promote.md", "prune.md"],
            "rules": ["common"],
            "skills": ["continuous-learning-v2", "continuous-learning", "knowledge-ops", "context-budget"],
            "agents": ["conversation-analyzer.md", "code-explorer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "ops-runtime-pack": {
        "schema_version": 1,
        "id": "ops-runtime-pack",
        "type": "pack",
        "name_zh": "运行时 / 成本运维包",
        "description_zh": "添加 PM2、包管理器初始化、成本报告和 ECC 自动更新命令。",
        "required": {
            "commands": ["pm2.md", "setup-pm.md", "cost-report.md", "auto-update.md"],
            "rules": ["common"],
            "skills": ["deployment-patterns", "cost-tracking", "terminal-ops", "flox-environments"],
            "agents": ["performance-optimizer.md", "code-explorer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "ecc-governance-pack": {
        "schema_version": 1,
        "id": "ecc-governance-pack",
        "type": "pack",
        "name_zh": "ECC 治理包",
        "description_zh": "添加 ECC 指南、skill 创建/健康检查、codemap 更新和 hookify 配置命令。",
        "required": {
            "commands": ["ecc-guide.md", "skill-create.md", "skill-health.md", "update-codemaps.md", "hookify.md", "hookify-configure.md", "hookify-list.md", "hookify-help.md"],
            "rules": ["common"],
            "skills": ["ecc-guide", "configure-ecc", "hookify-rules", "agent-sort", "documentation-lookup"],
            "agents": ["code-explorer.md", "docs-lookup.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "language-python-pack": {
        "schema_version": 1,
        "id": "language-python-pack",
        "type": "pack",
        "name_zh": "Python 语言包",
        "description_zh": "添加 Python / FastAPI review 命令、测试技能和 reviewer。",
        "required": {
            "commands": ["python-review.md", "fastapi-review.md"],
            "rules": ["python"],
            "skills": ["python-patterns", "python-testing", "fastapi-patterns", "tdd-workflow", "verification-loop"],
            "agents": ["python-reviewer.md", "fastapi-reviewer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "language-cpp-pack": {
        "schema_version": 1,
        "id": "language-cpp-pack",
        "type": "pack",
        "name_zh": "C++ 语言包",
        "description_zh": "添加 C++ build / review / test 命令、规则和 reviewer。",
        "required": {
            "commands": ["cpp-build.md", "cpp-review.md", "cpp-test.md"],
            "rules": ["cpp"],
            "skills": ["cpp-coding-standards", "cpp-testing", "tdd-workflow", "verification-loop"],
            "agents": ["cpp-build-resolver.md", "cpp-reviewer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "language-go-pack": {
        "schema_version": 1,
        "id": "language-go-pack",
        "type": "pack",
        "name_zh": "Go 语言包",
        "description_zh": "添加 Go build / review / test 命令、规则和 reviewer。",
        "required": {
            "commands": ["go-build.md", "go-review.md", "go-test.md"],
            "rules": ["golang"],
            "skills": ["golang-patterns", "golang-testing", "tdd-workflow", "verification-loop"],
            "agents": ["go-build-resolver.md", "go-reviewer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "language-rust-pack": {
        "schema_version": 1,
        "id": "language-rust-pack",
        "type": "pack",
        "name_zh": "Rust 语言包",
        "description_zh": "添加 Rust build / review / test 命令、规则和 reviewer。",
        "required": {
            "commands": ["rust-build.md", "rust-review.md", "rust-test.md"],
            "rules": ["rust"],
            "skills": ["rust-patterns", "rust-testing", "tdd-workflow", "verification-loop"],
            "agents": ["rust-build-resolver.md", "rust-reviewer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "language-flutter-dart-pack": {
        "schema_version": 1,
        "id": "language-flutter-dart-pack",
        "type": "pack",
        "name_zh": "Flutter / Dart 语言包",
        "description_zh": "添加 Flutter build / review / test 命令、Dart 规则和 reviewer。",
        "required": {
            "commands": ["flutter-build.md", "flutter-review.md", "flutter-test.md"],
            "rules": ["dart"],
            "skills": ["flutter-dart-code-review", "dart-flutter-patterns", "tdd-workflow", "verification-loop"],
            "agents": ["dart-build-resolver.md", "flutter-reviewer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
    "language-kotlin-pack": {
        "schema_version": 1,
        "id": "language-kotlin-pack",
        "type": "pack",
        "name_zh": "Kotlin / Android 语言包",
        "description_zh": "添加 Kotlin build / review / test 命令、规则和 reviewer。",
        "required": {
            "commands": ["kotlin-build.md", "kotlin-review.md", "kotlin-test.md", "gradle-build.md"],
            "rules": ["kotlin"],
            "skills": ["kotlin-patterns", "kotlin-testing", "kotlin-coroutines-flows", "tdd-workflow", "verification-loop"],
            "agents": ["kotlin-build-resolver.md", "kotlin-reviewer.md"],
            "runtime": [],
        },
        "optional": {"hooks": [], "mcp": [], "external_install": []},
    },
}


COMMAND_DEPENDENCIES = {
    "schema_version": 1,
    "commands": {
        "plan.md": {
            "mode": "safe-single",
            "required": {"commands": [], "skills": [], "agents": [], "rules": [], "runtime": []},
            "optional": {
                "commands": ["plan-prd.md"],
                "skills": ["context-budget", "strategic-compact"],
                "agents": ["planner.md"],
                "rules": [],
                "runtime": [],
                "mcp": [],
                "external_install": [],
            },
        },
        "multi-plan.md": {
            "mode": "runtime-required",
            "required": {
                "commands": ["multi-execute.md", "multi-backend.md", "multi-frontend.md", "multi-workflow.md"],
                "skills": [],
                "agents": [],
                "rules": [],
                "runtime": ["ccg-workflow"],
            },
            "optional": {
                "commands": [],
                "skills": [],
                "agents": [],
                "rules": [],
                "runtime": [],
                "mcp": ["ace-tool"],
                "external_install": ["npx ccg-workflow"],
            },
        },
    },
}


PROFILE_ENGLISH = {
    "ph-init": ("Early Project", "Best for early 0-to-1 projects focused on requirements, MVP scope, technical choices, and architecture planning."),
    "ph-build": ("Feature Build", "Best for building MVP and core features with small iterations and a tight validation loop."),
    "ph-onboard": ("Existing Project Onboarding", "Best for first understanding an existing project structure, stack, key modules, and validation commands."),
    "ph-iterate": ("Existing Project Iteration", "Best for feature iteration after understanding the current structure, with small changes that follow local patterns."),
    "ph-qa": ("Late Quality Check", "Best for build fixes, code review, test coverage, and security checks after core functionality is mostly complete."),
    "ph-launch": ("Pre-launch Release", "Best for final security, deployment, performance, cost, and quality checks before release."),
    "arch-web-saas-next-postgres": ("Website / SaaS Full Stack", "Complete web app architecture: Next.js frontend, TypeScript, API, Postgres, Prisma, migrations, and error handling."),
    "arch-ai-agent-fastapi-web": ("AI Agent App", "Complete AI app architecture: Python agent, FastAPI API, Web UI, evals, prompt optimization, and cost control."),
    "arch-crawler-data-platform": ("Crawler and Data Platform", "Complete data platform architecture: Python ingestion, data cleaning, Postgres storage, API service, and lightweight web UI."),
    "arch-browser-extension-with-api": ("Browser Extension + API", "Complete extension architecture: Chrome extension, Web UI, E2E, security checks, and Node API backend."),
    "arch-devops-automation-platform": ("DevOps Automation Platform", "Complete automation platform architecture: Python automation scripts, Docker, deployment, security, cost, and network checks."),
    "saas-next-fullstack": ("Next.js SaaS Full Stack", "For Next.js / TypeScript / SaaS full-stack projects."),
    "web-react-frontend": ("React Frontend", "For React / TypeScript / Web UI projects."),
    "api-node-backend": ("Node API Backend", "For Node.js / NestJS / TypeScript API services."),
    "api-python-fastapi": ("FastAPI Backend", "For Python / FastAPI API services."),
    "api-python-django": ("Django Backend", "For Python / Django backend projects."),
    "ai-agent-python": ("Python AI Agent", "For Python agents, LLM workflows, evals, and agent harness projects."),
    "automation-script-python": ("Python Automation Scripts", "For local automation, ops scripts, and small CLI tools."),
    "crawler-python-data": ("Python Crawling and Data", "For crawling, data ingestion, cleaning, and storage projects."),
    "browser-extension-chrome": ("Chrome Browser Extension", "For Chrome extension / WebExtension projects."),
    "ml-python-pipeline": ("Python ML Pipeline", "For machine learning, eval, and experiment pipelines."),
    "infra-docker-devops": ("Docker / DevOps", "For Docker, deployment, infrastructure, and network configuration checks."),
    "code-review-pack": ("Code Review Pack", "Adds commands, skills, and agents for local code review."),
    "build-fix-pack": ("Build Fix Pack", "Adds capabilities for locating build failures, type errors, and silent failures."),
    "test-coverage-pack": ("Test Coverage Pack", "Adds test coverage analysis and test-writing capabilities."),
    "security-audit-pack": ("Security Audit Pack", "Adds security scanning, production audit, and security reviewer capabilities."),
    "content-docs-pack": ("Docs Update Pack", "Adds README, help docs, product copy, and documentation update capabilities."),
    "research-writing-pack": ("Research Writing Pack", "Adds deep research, market research, and product capability analysis."),
    "seo-content-pack": ("SEO Content Pack", "Adds SEO content, brand voice, and content production capabilities."),
    "multi-model-planning-pack": ("Multi-model Planning Pack", "Adds multi-* planning commands. External ccg-workflow runtime and ace-tool MCP require separate confirmation."),
    "prp-workflow-pack": ("PRP Requirements-to-Delivery Pack", "Adds PRP planning, requirements, implementation, commit, and PR workflow commands."),
    "github-pr-pack": ("GitHub / PR Collaboration Pack", "Adds PR creation, PR review, GitHub collaboration, and multi-reviewer analysis capabilities."),
    "session-memory-pack": ("Session / Memory Management Pack", "Adds session save/resume, project lists, checkpoints, and aside-question capabilities."),
    "continuous-learning-pack": ("Continuous Learning Pack", "Adds long-term learning and capability refinement commands such as learn, instinct, evolve, promote, and prune."),
    "ops-runtime-pack": ("Runtime / Cost Ops Pack", "Adds PM2, package-manager setup, cost reporting, and ECC auto-update commands."),
    "ecc-governance-pack": ("ECC Governance Pack", "Adds ECC guides, skill creation/health checks, codemap updates, and hookify configuration commands."),
    "language-python-pack": ("Python Language Pack", "Adds Python / FastAPI review commands, testing skills, and reviewers."),
    "language-cpp-pack": ("C++ Language Pack", "Adds C++ build / review / test commands, rules, and reviewers."),
    "language-go-pack": ("Go Language Pack", "Adds Go build / review / test commands, rules, and reviewers."),
    "language-rust-pack": ("Rust Language Pack", "Adds Rust build / review / test commands, rules, and reviewers."),
    "language-flutter-dart-pack": ("Flutter / Dart Language Pack", "Adds Flutter build / review / test commands, Dart rules, and reviewers."),
    "language-kotlin-pack": ("Kotlin / Android Language Pack", "Adds Kotlin build / review / test commands, rules, and reviewers."),
}


def apply_profile_english() -> None:
    for group in (PHASES, ARCHITECTURES, PROJECT_TYPES, PACKS):
        for profile_id, profile in group.items():
            name, description = PROFILE_ENGLISH.get(profile_id, (None, None))
            if name:
                profile.setdefault("name_en", name)
            if description:
                profile.setdefault("description_en", description)


apply_profile_english()


def all_profiles():
    return {"phases": PHASES, "architectures": ARCHITECTURES, "project-types": PROJECT_TYPES, "packs": PACKS}
